version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  execute_tests: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: 
          command: yarn --frozen-lockfile
          name: install node packages
      - run:
          command: yarn test
          name: Run tests
      - run:
          command: yarn build
          name: Build app
workflows:
  test_my_app:
    jobs:
      - execute_tests
     